### ISSUE TITLE
Compilation issue for 76X release

### ISSUE THREAD

**Issue by zdemirog** [cms-jet/JetMETAnalysis#16]
Dear experts,
We are working on low pt L2Res measurement by using 2015D low PU data samples. We need to re-derive MCTruth corrections to improve and reduce uncertainties.
Our MC sample[1] is reconstructed with CMSSW_7_6_3, I have setup this CMSSW release and checked-out the latest version of the JetMETAnalysis repository. But the compilation is not successful, I am getting the following error;

afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetUtilities/interface/JRAEvent.h:188:38: error: no member named
      'Internal' in namespace 'ROOT'
   bool             CheckValue(ROOT::Internal::TTreeReaderValueBase* value);
                               ~~~~~~^
Error: rootcling: compilation failure (tmp/slc6_amd64_gcc493/src/JetMETAnalysis/JetUtilities/src/JetMETAnalysisJetUtilities/a/JetMETAnalysisJetUtilities_xrf9c1313670_dictUmbrella.h)

I have also tried to compile this package with the following CMSSW versions and are getting the same error.
CMSSW_7_6_3_patch1 / CMSSW_7_6_3_patch2  / CMSSW_7_6_4  / CMSSW_7_6_7  

Any suggestions would be greatly appreciated.
Best regards,
Zuhal

[1]: https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8%2FRunIIFall15MiniAODv2-25nsNoPURaw_magnetOn_76X_mcRun2_asymptotic_v12-v1%2FMINIAODSIM

**Comment by aperloff** [comment]
Hi Zuhal,

76X is very old and JetMETAnalysis typically tracks the latest CMSSW release. In order to use JetMETAnalysis for 76X you will need to check out an old commit. Alternatively you could look up the ROOT version used in 76X and update ROOT::Internal::TTreeReaderValueBase to the namespace used by that version of ROOT (assuming TTreeReaderValueBase simply changed namespaces).

Cheers,
Alexx Perloff

**Comment by zdemirog** [comment]
Dear Alexx,
Thank you for your suggestion. 
According to your suggestion, replacing the ROOT::Internal::TTreeReaderValueBase with ROOT::TTreeReaderValueBase, it solves the first compilation problem. 
Then, some other errors show up[1,2].
About [1] error: XrdClFileSystem is not work until 81X, so I removed the related parts from the jet_correction_analyzer_x.cc.
About [2] error: I couldn’t fix this error. 
I am not sure that the jet_l1_correction_x.cc is still required for the noPU MC sample. If not, removing this code from the package can also help me solve this error or do you have any suggestion to fix this error without removing the code from the package?

Best regards,
Zuhal

[1]: In file included from /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_correction_analyzer_x.cc:22:0:
/usr/include/xrootd/XrdCl/XrdClFileSystem.hh:31:36: fatal error: XrdOuc/XrdOucCompiler.hh: No such file or directory
 #include "XrdOuc/XrdOucCompiler.hh"
                                    ^
compilation terminated.

[2]: /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc: In function 'int main(int, char**)':
/afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc:206:73: error: use of deleted function 'std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)'
     ofstream outF = createTxtFile(txtFilename,spline_function,forTesting);
                                                                         ^
In file included from /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc:13:0:
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/fstream:602:11: note: 'std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)' is implicitly deleted because the default definition would be ill-formed:
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/fstream:602:11: error: use of deleted function 'std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)'
In file included from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/iostream:39:0,
                 from /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc:10:
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/ostream:58:11: note: 'std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)' is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/ostream:58:11: error: use of deleted function 'std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)'
In file included from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/ios:44:0,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/ostream:38,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/iostream:39,
                 from /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc:10:
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/bits/basic_ios.h:66:11: note: 'std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)' is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/ios:42:0,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/ostream:38,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/iostream:39,
                 from /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc:10:
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/bits/ios_base.h:786:5: error: 'std::ios_base::ios_base(const std::ios_base&)' is private
     ios_base(const ios_base&);
     ^
In file included from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/ios:44:0,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/ostream:38,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/iostream:39,
                 from /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc:10:
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc:13:0:
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/fstream:602:11: error: use of deleted function 'std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)'
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/fstream:602:11: error: use of deleted function 'std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)'
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/fstream:72:11: note: 'std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)' is implicitly deleted because the default definition would be ill-formed:
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/ios:43:0,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/ostream:38,
                 from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/iostream:39,
                 from /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc:10:
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/streambuf:802:7: error: 'std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]' is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc:13:0:
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/gcc/4.9.3/include/c++/4.9.3/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
/afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc: In function 'std::ofstream createTxtFile(std::string, std::string, bool)':
/afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetAnalyzers/bin/jet_l1_correction_x.cc:789:12: error: use of deleted function 'std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)'
     return outF;
            ^

**Comment by aperloff** [comment]
Hi Zuhal,

You are right, jet_l1_correction_x.cc is not needed to make the standard JECs. You can remove it or set it to not be compiled by scram (see BuildFile.xml). The error seems to stem from returning an ofstream and something to do with references, but I am not yet sure how to solve this.

Cheers,
Alexx

**Comment by zdemirog** [comment]
Hi Alexx,
Thank you very much for the confirmation and your time.
As you said, I set it to not be compiled by scram in the JetAnalyzers/bin/BuildFile.xml file. After that, I was facing another error [1].
The binIndexN function is defined in 91X[2] and later versions as far as I understand[3]. 
I couldn’t see any information about the test_jet_corrector_x in the README files. Can we also say that it is not needed to make the standard JECs?
I have made a test assuming that the answer to the above question was positive, I also set it to not be compiled by scram in the JetUtilities/bin/BuildFile.xml.
Then, the framework is successfully compiled.

Best regards,
Zuhal

[1]: /afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetUtilities/bin/test_jet_corrector_x.cc:50:14: error: 'class JetCorrectorParameters' has no member named 'binIndexN'
    L1JetPar->binIndexN(fX);
              ^
/afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetUtilities/bin/test_jet_corrector_x.cc: In function 'void compareJCP()':
/afs/cern.ch/work/z/zdemirog/private/MCTruth/CMSSW_7_6_3/src/JetMETAnalysis/JetUtilities/bin/test_jet_corrector_x.cc:75:28: error: 'class JetCorrectorParameters' has no member named 'binIndexN'
     int newBin = L1JetPar->binIndexN(fX);
                            ^

[2]: 
https://github.com/cms-sw/cmssw/blob/CMSSW_9_1_X/CondFormats/JetMETObjects/interface/JetCorrectorParameters.h#L106

[3]: https://indico.cern.ch/event/617090/contributions/2490770/attachments/1420000/2175622/2017_02_23-Alexx-JetCorrectorParameters.pdf

**Comment by aperloff** [comment]
Correct, you do not need test_jet_corrector_x. I’m glad you were able to get the package to compile.

Cheers,
Alexx

**Comment by zdemirog** [comment]
Dear Alexx,
Many thanks for your help, and for your explanations. 

Best regards,
Zuhal
